package com.moxiao.studypilot.agent.domain;

public enum AgentScope {
    MATERIAL_PROCESSING,
    QUIZ_GENERATION,
    PLAN_GENERATION,
    TASK_MANAGEMENT,
    SMALL_PLAN_ADJUSTMENT,
    LARGE_PLAN_ADJUSTMENT,
    LEARNING_MANAGEMENT,
    SETTINGS_MANAGEMENT,
    NOTIFICATION_MANAGEMENT,
    WORKSPACE_MANAGEMENT,
    ARTIFACT_MANAGEMENT,
    ROADMAP_MANAGEMENT
}
