package com.moxiao.studypilot.agent.domain;

public enum ExecutionType {
    MATERIAL_PROCESSING,
    QUIZ_GENERATION,
    PLAN_GENERATION,
    PLAN_ADJUSTMENT,
    TASK_STATUS_CHANGE,
    WEB_SEARCH,
    LEARNING_GOAL_CHANGE,
    USER_SETTINGS_CHANGE,
    NOTIFICATION_CHANGE,
    WORKSPACE_REGISTRATION,
    ARTIFACT_SUBMISSION,
    ROADMAP_CHANGE,
    RUNNER_EXECUTION,
    CODE_PATCH_APPLICATION,
    GIT_COMMIT,
    GIT_PUSH,
    /** Task 33：受控本地界面兜底动作（可审计的本机副作用）。 */
    LOCAL_INTERFACE_AUTOMATION
}
