package com.moxiao.studypilot.agent.domain;

public enum ExecutionType {
    MATERIAL_PROCESSING,
    QUIZ_GENERATION,
    PLAN_GENERATION,
    PLAN_ADJUSTMENT,
    TASK_STATUS_CHANGE,
    WEB_SEARCH,
    LEARNING_GOAL_CHANGE,
    USER_SETTINGS_CHANGE,
    NOTIFICATION_CHANGE,
    WORKSPACE_REGISTRATION,
    ARTIFACT_SUBMISSION,
    ROADMAP_CHANGE
}
